name: actions-config-validation
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments

jobs:
  actions-config-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: actions-config-validation
        uses: GrantBirki/json-yaml-validate@3add42f5fa8bfff04a3fe664d27a316736257ef1 # pin@v2.3.1
        with:
          comment: "true" # enable comment mode
          exclude_file: ".github/config/exclude.txt"
